// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef CXX___XML_XSD_SAD_PSKEL_H
#define CXX___XML_XSD_SAD_PSKEL_H

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 3030000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

// Forward declarations
//
namespace sad
{
  class softwareassembly_pskel;
  class componentfiles_pskel;
  class componentfile_pskel;
  class localfile_pskel;
  class partitioning_pskel;
  class componentplacement_pskel;
  class componentfileref_pskel;
  class componentinstantiation_pskel;
  class componentproperties_pskel;
  class findcomponent_pskel;
  class componentresourcefactoryref_pskel;
  class devicethatloadedthiscomponentref_pskel;
  class deviceusedbythiscomponentref_pskel;
  class resourcefactoryproperties_pskel;
  class simpleref_pskel;
  class simplesequenceref_pskel;
  class structref_pskel;
  class structsequenceref_pskel;
  class structvalue_pskel;
  class values_pskel;
  class componentinstantiationref_pskel;
  class findby_pskel;
  class namingservice_pskel;
  class domainfinder_pskel;
  class hostcollocation_pskel;
  class assemblycontroller_pskel;
  class connections_pskel;
  class connectinterface_pskel;
  class usesport_pskel;
  class providesport_pskel;
  class componentsupportedinterface_pskel;
  class externalports_pskel;
  class port_pskel;
}


#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_PARSER_USE_CHAR
#define XSD_CXX_PARSER_USE_CHAR
#endif

#include <xsd/cxx/xml/error-handler.hxx>
#include <xsd/cxx/parser/exceptions.hxx>
#include <xsd/cxx/parser/elements.hxx>
#include <xsd/cxx/parser/xml-schema.hxx>
#include <xsd/cxx/parser/validating/parser.hxx>
#include <xsd/cxx/parser/validating/exceptions.hxx>
#include <xsd/cxx/parser/validating/xml-schema-pskel.hxx>
#include <xsd/cxx/parser/validating/xml-schema-pimpl.hxx>
#include <xsd/cxx/parser/expat/elements.hxx>

#include "memory"
#include "map"
#include "../include/ossie/SoftwareAssembly.h"

namespace xml_schema
{
  // Built-in XML Schema types mapping.
  //
  typedef ::xsd::cxx::parser::string_sequence< char > string_sequence;
  typedef ::xsd::cxx::parser::qname< char > qname;
  typedef ::xsd::cxx::parser::buffer buffer;
  typedef ::xsd::cxx::parser::time_zone time_zone;
  typedef ::xsd::cxx::parser::gday gday;
  typedef ::xsd::cxx::parser::gmonth gmonth;
  typedef ::xsd::cxx::parser::gyear gyear;
  typedef ::xsd::cxx::parser::gmonth_day gmonth_day;
  typedef ::xsd::cxx::parser::gyear_month gyear_month;
  typedef ::xsd::cxx::parser::date date;
  typedef ::xsd::cxx::parser::time time;
  typedef ::xsd::cxx::parser::date_time date_time;
  typedef ::xsd::cxx::parser::duration duration;

  // Base parser skeletons.
  //
  typedef ::xsd::cxx::parser::parser_base< char > parser_base;
  typedef ::xsd::cxx::parser::validating::empty_content< char > empty_content;
  typedef ::xsd::cxx::parser::validating::simple_content< char > simple_content;
  typedef ::xsd::cxx::parser::validating::complex_content< char > complex_content;
  typedef ::xsd::cxx::parser::validating::list_base< char > list_base;

  // Parser skeletons and implementations for the XML Schema
  // built-in types.
  //
  typedef ::xsd::cxx::parser::validating::any_type_pskel< char > any_type_pskel;
  typedef ::xsd::cxx::parser::validating::any_type_pimpl< char > any_type_pimpl;

  typedef ::xsd::cxx::parser::validating::any_simple_type_pskel< char > any_simple_type_pskel;
  typedef ::xsd::cxx::parser::validating::any_simple_type_pimpl< char > any_simple_type_pimpl;

  typedef ::xsd::cxx::parser::validating::byte_pskel< char > byte_pskel;
  typedef ::xsd::cxx::parser::validating::byte_pimpl< char > byte_pimpl;

  typedef ::xsd::cxx::parser::validating::unsigned_byte_pskel< char > unsigned_byte_pskel;
  typedef ::xsd::cxx::parser::validating::unsigned_byte_pimpl< char > unsigned_byte_pimpl;

  typedef ::xsd::cxx::parser::validating::short_pskel< char > short_pskel;
  typedef ::xsd::cxx::parser::validating::short_pimpl< char > short_pimpl;

  typedef ::xsd::cxx::parser::validating::unsigned_short_pskel< char > unsigned_short_pskel;
  typedef ::xsd::cxx::parser::validating::unsigned_short_pimpl< char > unsigned_short_pimpl;

  typedef ::xsd::cxx::parser::validating::int_pskel< char > int_pskel;
  typedef ::xsd::cxx::parser::validating::int_pimpl< char > int_pimpl;

  typedef ::xsd::cxx::parser::validating::unsigned_int_pskel< char > unsigned_int_pskel;
  typedef ::xsd::cxx::parser::validating::unsigned_int_pimpl< char > unsigned_int_pimpl;

  typedef ::xsd::cxx::parser::validating::long_pskel< char > long_pskel;
  typedef ::xsd::cxx::parser::validating::long_pimpl< char > long_pimpl;

  typedef ::xsd::cxx::parser::validating::unsigned_long_pskel< char > unsigned_long_pskel;
  typedef ::xsd::cxx::parser::validating::unsigned_long_pimpl< char > unsigned_long_pimpl;

  typedef ::xsd::cxx::parser::validating::integer_pskel< char > integer_pskel;
  typedef ::xsd::cxx::parser::validating::integer_pimpl< char > integer_pimpl;

  typedef ::xsd::cxx::parser::validating::non_positive_integer_pskel< char > non_positive_integer_pskel;
  typedef ::xsd::cxx::parser::validating::non_positive_integer_pimpl< char > non_positive_integer_pimpl;

  typedef ::xsd::cxx::parser::validating::non_negative_integer_pskel< char > non_negative_integer_pskel;
  typedef ::xsd::cxx::parser::validating::non_negative_integer_pimpl< char > non_negative_integer_pimpl;

  typedef ::xsd::cxx::parser::validating::positive_integer_pskel< char > positive_integer_pskel;
  typedef ::xsd::cxx::parser::validating::positive_integer_pimpl< char > positive_integer_pimpl;

  typedef ::xsd::cxx::parser::validating::negative_integer_pskel< char > negative_integer_pskel;
  typedef ::xsd::cxx::parser::validating::negative_integer_pimpl< char > negative_integer_pimpl;

  typedef ::xsd::cxx::parser::validating::boolean_pskel< char > boolean_pskel;
  typedef ::xsd::cxx::parser::validating::boolean_pimpl< char > boolean_pimpl;

  typedef ::xsd::cxx::parser::validating::float_pskel< char > float_pskel;
  typedef ::xsd::cxx::parser::validating::float_pimpl< char > float_pimpl;

  typedef ::xsd::cxx::parser::validating::double_pskel< char > double_pskel;
  typedef ::xsd::cxx::parser::validating::double_pimpl< char > double_pimpl;

  typedef ::xsd::cxx::parser::validating::decimal_pskel< char > decimal_pskel;
  typedef ::xsd::cxx::parser::validating::decimal_pimpl< char > decimal_pimpl;

  typedef ::xsd::cxx::parser::validating::string_pskel< char > string_pskel;
  typedef ::xsd::cxx::parser::validating::string_pimpl< char > string_pimpl;

  typedef ::xsd::cxx::parser::validating::normalized_string_pskel< char > normalized_string_pskel;
  typedef ::xsd::cxx::parser::validating::normalized_string_pimpl< char > normalized_string_pimpl;

  typedef ::xsd::cxx::parser::validating::token_pskel< char > token_pskel;
  typedef ::xsd::cxx::parser::validating::token_pimpl< char > token_pimpl;

  typedef ::xsd::cxx::parser::validating::name_pskel< char > name_pskel;
  typedef ::xsd::cxx::parser::validating::name_pimpl< char > name_pimpl;

  typedef ::xsd::cxx::parser::validating::nmtoken_pskel< char > nmtoken_pskel;
  typedef ::xsd::cxx::parser::validating::nmtoken_pimpl< char > nmtoken_pimpl;

  typedef ::xsd::cxx::parser::validating::nmtokens_pskel< char > nmtokens_pskel;
  typedef ::xsd::cxx::parser::validating::nmtokens_pimpl< char > nmtokens_pimpl;

  typedef ::xsd::cxx::parser::validating::ncname_pskel< char > ncname_pskel;
  typedef ::xsd::cxx::parser::validating::ncname_pimpl< char > ncname_pimpl;

  typedef ::xsd::cxx::parser::validating::language_pskel< char > language_pskel;
  typedef ::xsd::cxx::parser::validating::language_pimpl< char > language_pimpl;

  typedef ::xsd::cxx::parser::validating::id_pskel< char > id_pskel;
  typedef ::xsd::cxx::parser::validating::id_pimpl< char > id_pimpl;

  typedef ::xsd::cxx::parser::validating::idref_pskel< char > idref_pskel;
  typedef ::xsd::cxx::parser::validating::idref_pimpl< char > idref_pimpl;

  typedef ::xsd::cxx::parser::validating::idrefs_pskel< char > idrefs_pskel;
  typedef ::xsd::cxx::parser::validating::idrefs_pimpl< char > idrefs_pimpl;

  typedef ::xsd::cxx::parser::validating::uri_pskel< char > uri_pskel;
  typedef ::xsd::cxx::parser::validating::uri_pimpl< char > uri_pimpl;

  typedef ::xsd::cxx::parser::validating::qname_pskel< char > qname_pskel;
  typedef ::xsd::cxx::parser::validating::qname_pimpl< char > qname_pimpl;

  typedef ::xsd::cxx::parser::validating::base64_binary_pskel< char > base64_binary_pskel;
  typedef ::xsd::cxx::parser::validating::base64_binary_pimpl< char > base64_binary_pimpl;

  typedef ::xsd::cxx::parser::validating::hex_binary_pskel< char > hex_binary_pskel;
  typedef ::xsd::cxx::parser::validating::hex_binary_pimpl< char > hex_binary_pimpl;

  typedef ::xsd::cxx::parser::validating::date_pskel< char > date_pskel;
  typedef ::xsd::cxx::parser::validating::date_pimpl< char > date_pimpl;

  typedef ::xsd::cxx::parser::validating::date_time_pskel< char > date_time_pskel;
  typedef ::xsd::cxx::parser::validating::date_time_pimpl< char > date_time_pimpl;

  typedef ::xsd::cxx::parser::validating::duration_pskel< char > duration_pskel;
  typedef ::xsd::cxx::parser::validating::duration_pimpl< char > duration_pimpl;

  typedef ::xsd::cxx::parser::validating::gday_pskel< char > gday_pskel;
  typedef ::xsd::cxx::parser::validating::gday_pimpl< char > gday_pimpl;

  typedef ::xsd::cxx::parser::validating::gmonth_pskel< char > gmonth_pskel;
  typedef ::xsd::cxx::parser::validating::gmonth_pimpl< char > gmonth_pimpl;

  typedef ::xsd::cxx::parser::validating::gmonth_day_pskel< char > gmonth_day_pskel;
  typedef ::xsd::cxx::parser::validating::gmonth_day_pimpl< char > gmonth_day_pimpl;

  typedef ::xsd::cxx::parser::validating::gyear_pskel< char > gyear_pskel;
  typedef ::xsd::cxx::parser::validating::gyear_pimpl< char > gyear_pimpl;

  typedef ::xsd::cxx::parser::validating::gyear_month_pskel< char > gyear_month_pskel;
  typedef ::xsd::cxx::parser::validating::gyear_month_pimpl< char > gyear_month_pimpl;

  typedef ::xsd::cxx::parser::validating::time_pskel< char > time_pskel;
  typedef ::xsd::cxx::parser::validating::time_pimpl< char > time_pimpl;

  // Exceptions. See libxsd/xsd/cxx/parser/exceptions.hxx for details.
  //
  typedef ::xsd::cxx::parser::exception< char > exception;

  // Parsing diagnostics.
  //
  typedef ::xsd::cxx::parser::severity severity;
  typedef ::xsd::cxx::parser::error< char > error;
  typedef ::xsd::cxx::parser::diagnostics< char > diagnostics;
  typedef ::xsd::cxx::parser::parsing< char > parsing;

  // Error handler. See libxsd/xsd/cxx/xml/error-handler.hxx for details.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // Read-only string.
  //
  typedef ::xsd::cxx::ro_string< char > ro_string;

  // Document type. See libxsd/xsd/cxx/parser/expat/elements.hxx
  // for details.
  //
  typedef ::xsd::cxx::parser::expat::document< char > document;
}

namespace sad
{
  class softwareassembly_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    description (const ::std::string&);

    virtual void
    componentfiles (const ::std::vector<ossie::ComponentFile>&);

    virtual void
    partitioning (const ossie::SoftwareAssembly::Partitioning&);

    virtual void
    assemblycontroller (const ::std::string&);

    virtual void
    connections (const ::std::vector<ossie::Connection>&);

    virtual void
    externalports (const ::std::vector<ossie::SoftwareAssembly::Port>&);

    virtual void
    id (const ::std::string&);

    virtual void
    name (const ::std::string&);

    virtual void
    version (const ::std::string&);

    virtual ::std::auto_ptr<ossie::SoftwareAssembly::SAD>
    post_softwareassembly () = 0;

    // Parser construction API.
    //
    void
    description_parser (::xml_schema::string_pskel&);

    void
    componentfiles_parser (::sad::componentfiles_pskel&);

    void
    partitioning_parser (::sad::partitioning_pskel&);

    void
    assemblycontroller_parser (::sad::assemblycontroller_pskel&);

    void
    connections_parser (::sad::connections_pskel&);

    void
    externalports_parser (::sad::externalports_pskel&);

    void
    id_parser (::xml_schema::string_pskel&);

    void
    name_parser (::xml_schema::string_pskel&);

    void
    version_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* description */,
             ::sad::componentfiles_pskel& /* componentfiles */,
             ::sad::partitioning_pskel& /* partitioning */,
             ::sad::assemblycontroller_pskel& /* assemblycontroller */,
             ::sad::connections_pskel& /* connections */,
             ::sad::externalports_pskel& /* externalports */,
             ::xml_schema::string_pskel& /* id */,
             ::xml_schema::string_pskel& /* name */,
             ::xml_schema::string_pskel& /* version */);

    // Constructor.
    //
    softwareassembly_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* description_parser_;
    ::sad::componentfiles_pskel* componentfiles_parser_;
    ::sad::partitioning_pskel* partitioning_parser_;
    ::sad::assemblycontroller_pskel* assemblycontroller_parser_;
    ::sad::connections_pskel* connections_parser_;
    ::sad::externalports_pskel* externalports_parser_;
    ::xml_schema::string_pskel* id_parser_;
    ::xml_schema::string_pskel* name_parser_;
    ::xml_schema::string_pskel* version_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::softwareassembly_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    protected:
    struct v_state_attr_
    {
      bool id;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class componentfiles_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    componentfile (const ::ossie::ComponentFile&);

    virtual ::std::vector<ossie::ComponentFile>
    post_componentfiles () = 0;

    // Parser construction API.
    //
    void
    componentfile_parser (::sad::componentfile_pskel&);

    void
    parsers (::sad::componentfile_pskel& /* componentfile */);

    // Constructor.
    //
    componentfiles_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::componentfile_pskel* componentfile_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::componentfiles_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class componentfile_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    localfile (const ::std::string&);

    virtual void
    id (const ::std::string&);

    virtual void
    type (const ::std::string&);

    virtual ::ossie::ComponentFile
    post_componentfile () = 0;

    // Parser construction API.
    //
    void
    localfile_parser (::sad::localfile_pskel&);

    void
    id_parser (::xml_schema::string_pskel&);

    void
    type_parser (::xml_schema::string_pskel&);

    void
    parsers (::sad::localfile_pskel& /* localfile */,
             ::xml_schema::string_pskel& /* id */,
             ::xml_schema::string_pskel& /* type */);

    // Constructor.
    //
    componentfile_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::sad::localfile_pskel* localfile_parser_;
    ::xml_schema::string_pskel* id_parser_;
    ::xml_schema::string_pskel* type_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::componentfile_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    protected:
    struct v_state_attr_
    {
      bool id;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class localfile_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    name (const ::std::string&);

    virtual ::std::string
    post_localfile () = 0;

    // Parser construction API.
    //
    void
    name_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* name */);

    // Constructor.
    //
    localfile_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* name_parser_;

    protected:
    struct v_state_attr_
    {
      bool name;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class partitioning_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    componentplacement (const ::ossie::ComponentPlacement&);

    virtual void
    hostcollocation (const ::ossie::SoftwareAssembly::HostCollocation&);

    virtual ossie::SoftwareAssembly::Partitioning
    post_partitioning () = 0;

    // Parser construction API.
    //
    void
    componentplacement_parser (::sad::componentplacement_pskel&);

    void
    hostcollocation_parser (::sad::hostcollocation_pskel&);

    void
    parsers (::sad::componentplacement_pskel& /* componentplacement */,
             ::sad::hostcollocation_pskel& /* hostcollocation */);

    // Constructor.
    //
    partitioning_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::componentplacement_pskel* componentplacement_parser_;
    ::sad::hostcollocation_pskel* hostcollocation_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::partitioning_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class componentplacement_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    componentfileref (const ::std::string&);

    virtual void
    componentinstantiation (const ::ossie::ComponentInstantiation&);

    virtual ::ossie::ComponentPlacement
    post_componentplacement () = 0;

    // Parser construction API.
    //
    void
    componentfileref_parser (::sad::componentfileref_pskel&);

    void
    componentinstantiation_parser (::sad::componentinstantiation_pskel&);

    void
    parsers (::sad::componentfileref_pskel& /* componentfileref */,
             ::sad::componentinstantiation_pskel& /* componentinstantiation */);

    // Constructor.
    //
    componentplacement_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::componentfileref_pskel* componentfileref_parser_;
    ::sad::componentinstantiation_pskel* componentinstantiation_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::componentplacement_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class componentfileref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    refid (const ::std::string&);

    virtual ::std::string
    post_componentfileref () = 0;

    // Parser construction API.
    //
    void
    refid_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* refid */);

    // Constructor.
    //
    componentfileref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* refid_parser_;

    protected:
    struct v_state_attr_
    {
      bool refid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class componentinstantiation_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    usagename (const ::std::string&);

    virtual void
    componentproperties (const ::std::vector<ossie::ComponentProperty*>&);

    virtual void
    findcomponent (const ::std::string&);

    virtual void
    id (const ::std::string&);

    virtual void
    startorder (const ::std::string&);

    virtual ::ossie::ComponentInstantiation
    post_componentinstantiation () = 0;

    // Parser construction API.
    //
    void
    usagename_parser (::xml_schema::string_pskel&);

    void
    componentproperties_parser (::sad::componentproperties_pskel&);

    void
    findcomponent_parser (::sad::findcomponent_pskel&);

    void
    id_parser (::xml_schema::string_pskel&);

    void
    startorder_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* usagename */,
             ::sad::componentproperties_pskel& /* componentproperties */,
             ::sad::findcomponent_pskel& /* findcomponent */,
             ::xml_schema::string_pskel& /* id */,
             ::xml_schema::string_pskel& /* startorder */);

    // Constructor.
    //
    componentinstantiation_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* usagename_parser_;
    ::sad::componentproperties_pskel* componentproperties_parser_;
    ::sad::findcomponent_pskel* findcomponent_parser_;
    ::xml_schema::string_pskel* id_parser_;
    ::xml_schema::string_pskel* startorder_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::componentinstantiation_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    protected:
    struct v_state_attr_
    {
      bool id;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class componentproperties_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    simpleref (ossie::SimplePropertyRef*);

    virtual void
    simplesequenceref (ossie::SimpleSequencePropertyRef*);

    virtual void
    structref (ossie::StructPropertyRef*);

    virtual void
    structsequenceref (ossie::StructSequencePropertyRef*);

    virtual ::std::vector<ossie::ComponentProperty*>
    post_componentproperties () = 0;

    // Parser construction API.
    //
    void
    simpleref_parser (::sad::simpleref_pskel&);

    void
    simplesequenceref_parser (::sad::simplesequenceref_pskel&);

    void
    structref_parser (::sad::structref_pskel&);

    void
    structsequenceref_parser (::sad::structsequenceref_pskel&);

    void
    parsers (::sad::simpleref_pskel& /* simpleref */,
             ::sad::simplesequenceref_pskel& /* simplesequenceref */,
             ::sad::structref_pskel& /* structref */,
             ::sad::structsequenceref_pskel& /* structsequenceref */);

    // Constructor.
    //
    componentproperties_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::simpleref_pskel* simpleref_parser_;
    ::sad::simplesequenceref_pskel* simplesequenceref_parser_;
    ::sad::structref_pskel* structref_parser_;
    ::sad::structsequenceref_pskel* structsequenceref_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::componentproperties_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class findcomponent_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    componentresourcefactoryref ();

    virtual void
    namingservice (const ::std::string&);

    virtual ::std::string
    post_findcomponent () = 0;

    // Parser construction API.
    //
    void
    componentresourcefactoryref_parser (::sad::componentresourcefactoryref_pskel&);

    void
    namingservice_parser (::sad::namingservice_pskel&);

    void
    parsers (::sad::componentresourcefactoryref_pskel& /* componentresourcefactoryref */,
             ::sad::namingservice_pskel& /* namingservice */);

    // Constructor.
    //
    findcomponent_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::componentresourcefactoryref_pskel* componentresourcefactoryref_parser_;
    ::sad::namingservice_pskel* namingservice_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::findcomponent_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class componentresourcefactoryref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    resourcefactoryproperties ();

    virtual void
    refid (const ::std::string&);

    virtual void
    post_componentresourcefactoryref ();

    // Parser construction API.
    //
    void
    resourcefactoryproperties_parser (::sad::resourcefactoryproperties_pskel&);

    void
    refid_parser (::xml_schema::string_pskel&);

    void
    parsers (::sad::resourcefactoryproperties_pskel& /* resourcefactoryproperties */,
             ::xml_schema::string_pskel& /* refid */);

    // Constructor.
    //
    componentresourcefactoryref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::sad::resourcefactoryproperties_pskel* resourcefactoryproperties_parser_;
    ::xml_schema::string_pskel* refid_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::componentresourcefactoryref_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    protected:
    struct v_state_attr_
    {
      bool refid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class devicethatloadedthiscomponentref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    refid (const ::std::string&);

    virtual ::std::string
    post_devicethatloadedthiscomponentref () = 0;

    // Parser construction API.
    //
    void
    refid_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* refid */);

    // Constructor.
    //
    devicethatloadedthiscomponentref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* refid_parser_;

    protected:
    struct v_state_attr_
    {
      bool refid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class deviceusedbythiscomponentref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    refid (const ::std::string&);

    virtual void
    usesrefid (const ::std::string&);

    virtual ::std::pair<std::string, std::string>
    post_deviceusedbythiscomponentref () = 0;

    // Parser construction API.
    //
    void
    refid_parser (::xml_schema::string_pskel&);

    void
    usesrefid_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* refid */,
             ::xml_schema::string_pskel& /* usesrefid */);

    // Constructor.
    //
    deviceusedbythiscomponentref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* refid_parser_;
    ::xml_schema::string_pskel* usesrefid_parser_;

    protected:
    struct v_state_attr_
    {
      bool refid;
      bool usesrefid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class resourcefactoryproperties_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    simpleref (ossie::SimplePropertyRef*);

    virtual void
    simplesequenceref (ossie::SimpleSequencePropertyRef*);

    virtual void
    structref (ossie::StructPropertyRef*);

    virtual void
    structsequenceref (ossie::StructSequencePropertyRef*);

    virtual void
    post_resourcefactoryproperties ();

    // Parser construction API.
    //
    void
    simpleref_parser (::sad::simpleref_pskel&);

    void
    simplesequenceref_parser (::sad::simplesequenceref_pskel&);

    void
    structref_parser (::sad::structref_pskel&);

    void
    structsequenceref_parser (::sad::structsequenceref_pskel&);

    void
    parsers (::sad::simpleref_pskel& /* simpleref */,
             ::sad::simplesequenceref_pskel& /* simplesequenceref */,
             ::sad::structref_pskel& /* structref */,
             ::sad::structsequenceref_pskel& /* structsequenceref */);

    // Constructor.
    //
    resourcefactoryproperties_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::simpleref_pskel* simpleref_parser_;
    ::sad::simplesequenceref_pskel* simplesequenceref_parser_;
    ::sad::structref_pskel* structref_parser_;
    ::sad::structsequenceref_pskel* structsequenceref_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::resourcefactoryproperties_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class simpleref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    refid (const ::std::string&);

    virtual void
    value (const ::std::string&);

    virtual ossie::SimplePropertyRef*
    post_simpleref () = 0;

    // Parser construction API.
    //
    void
    refid_parser (::xml_schema::string_pskel&);

    void
    value_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* refid */,
             ::xml_schema::string_pskel& /* value */);

    // Constructor.
    //
    simpleref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* refid_parser_;
    ::xml_schema::string_pskel* value_parser_;

    protected:
    struct v_state_attr_
    {
      bool refid;
      bool value;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class simplesequenceref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    values (const ::std::vector<std::string>&);

    virtual void
    refid (const ::std::string&);

    virtual ossie::SimpleSequencePropertyRef*
    post_simplesequenceref () = 0;

    // Parser construction API.
    //
    void
    values_parser (::sad::values_pskel&);

    void
    refid_parser (::xml_schema::string_pskel&);

    void
    parsers (::sad::values_pskel& /* values */,
             ::xml_schema::string_pskel& /* refid */);

    // Constructor.
    //
    simplesequenceref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::sad::values_pskel* values_parser_;
    ::xml_schema::string_pskel* refid_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::simplesequenceref_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    protected:
    struct v_state_attr_
    {
      bool refid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class structref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    simpleref (ossie::SimplePropertyRef*);

    virtual void
    refid (const ::std::string&);

    virtual ossie::StructPropertyRef*
    post_structref () = 0;

    // Parser construction API.
    //
    void
    simpleref_parser (::sad::simpleref_pskel&);

    void
    refid_parser (::xml_schema::string_pskel&);

    void
    parsers (::sad::simpleref_pskel& /* simpleref */,
             ::xml_schema::string_pskel& /* refid */);

    // Constructor.
    //
    structref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::sad::simpleref_pskel* simpleref_parser_;
    ::xml_schema::string_pskel* refid_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::structref_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    protected:
    struct v_state_attr_
    {
      bool refid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class structsequenceref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    structvalue (const ::std::map<std::string, std::string>&);

    virtual void
    refid (const ::std::string&);

    virtual ossie::StructSequencePropertyRef*
    post_structsequenceref () = 0;

    // Parser construction API.
    //
    void
    structvalue_parser (::sad::structvalue_pskel&);

    void
    refid_parser (::xml_schema::string_pskel&);

    void
    parsers (::sad::structvalue_pskel& /* structvalue */,
             ::xml_schema::string_pskel& /* refid */);

    // Constructor.
    //
    structsequenceref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::sad::structvalue_pskel* structvalue_parser_;
    ::xml_schema::string_pskel* refid_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::structsequenceref_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    protected:
    struct v_state_attr_
    {
      bool refid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class structvalue_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    simpleref (ossie::SimplePropertyRef*);

    virtual ::std::map<std::string, std::string>
    post_structvalue () = 0;

    // Parser construction API.
    //
    void
    simpleref_parser (::sad::simpleref_pskel&);

    void
    parsers (::sad::simpleref_pskel& /* simpleref */);

    // Constructor.
    //
    structvalue_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::simpleref_pskel* simpleref_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::structvalue_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class values_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    value (const ::std::string&);

    virtual ::std::vector<std::string>
    post_values () = 0;

    // Parser construction API.
    //
    void
    value_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* value */);

    // Constructor.
    //
    values_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::xml_schema::string_pskel* value_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::values_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class componentinstantiationref_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    refid (const ::std::string&);

    virtual ::std::string
    post_componentinstantiationref () = 0;

    // Parser construction API.
    //
    void
    refid_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* refid */);

    // Constructor.
    //
    componentinstantiationref_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* refid_parser_;

    protected:
    struct v_state_attr_
    {
      bool refid;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class findby_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    namingservice (const ::std::string&);

    virtual void
    stringifiedobjectref (const ::std::string&);

    virtual void
    domainfinder (const ::std::pair<std::string, std::string>&);

    virtual ::ossie::FindBy
    post_findby () = 0;

    // Parser construction API.
    //
    void
    namingservice_parser (::sad::namingservice_pskel&);

    void
    stringifiedobjectref_parser (::xml_schema::string_pskel&);

    void
    domainfinder_parser (::sad::domainfinder_pskel&);

    void
    parsers (::sad::namingservice_pskel& /* namingservice */,
             ::xml_schema::string_pskel& /* stringifiedobjectref */,
             ::sad::domainfinder_pskel& /* domainfinder */);

    // Constructor.
    //
    findby_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::namingservice_pskel* namingservice_parser_;
    ::xml_schema::string_pskel* stringifiedobjectref_parser_;
    ::sad::domainfinder_pskel* domainfinder_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::findby_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class namingservice_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    name (const ::std::string&);

    virtual ::std::string
    post_namingservice () = 0;

    // Parser construction API.
    //
    void
    name_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* name */);

    // Constructor.
    //
    namingservice_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* name_parser_;

    protected:
    struct v_state_attr_
    {
      bool name;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class domainfinder_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    type (const ::std::string&);

    virtual void
    name (const ::std::string&);

    virtual ::std::pair<std::string, std::string>
    post_domainfinder () = 0;

    // Parser construction API.
    //
    void
    type_parser (::xml_schema::string_pskel&);

    void
    name_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* type */,
             ::xml_schema::string_pskel& /* name */);

    // Constructor.
    //
    domainfinder_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::xml_schema::string_pskel* type_parser_;
    ::xml_schema::string_pskel* name_parser_;

    protected:
    struct v_state_attr_
    {
      bool type;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsd::cxx::parser::pod_stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class hostcollocation_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    componentplacement (const ::ossie::ComponentPlacement&);

    virtual void
    id (const ::std::string&);

    virtual void
    name (const ::std::string&);

    virtual ::ossie::SoftwareAssembly::HostCollocation
    post_hostcollocation () = 0;

    // Parser construction API.
    //
    void
    componentplacement_parser (::sad::componentplacement_pskel&);

    void
    id_parser (::xml_schema::string_pskel&);

    void
    name_parser (::xml_schema::string_pskel&);

    void
    parsers (::sad::componentplacement_pskel& /* componentplacement */,
             ::xml_schema::string_pskel& /* id */,
             ::xml_schema::string_pskel& /* name */);

    // Constructor.
    //
    hostcollocation_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::sad::componentplacement_pskel* componentplacement_parser_;
    ::xml_schema::string_pskel* id_parser_;
    ::xml_schema::string_pskel* name_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::hostcollocation_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class assemblycontroller_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    componentinstantiationref (const ::std::string&);

    virtual ::std::string
    post_assemblycontroller () = 0;

    // Parser construction API.
    //
    void
    componentinstantiationref_parser (::sad::componentinstantiationref_pskel&);

    void
    parsers (::sad::componentinstantiationref_pskel& /* componentinstantiationref */);

    // Constructor.
    //
    assemblycontroller_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::componentinstantiationref_pskel* componentinstantiationref_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::assemblycontroller_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class connections_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    connectinterface (const ::ossie::Connection&);

    virtual ::std::vector<ossie::Connection>
    post_connections () = 0;

    // Parser construction API.
    //
    void
    connectinterface_parser (::sad::connectinterface_pskel&);

    void
    parsers (::sad::connectinterface_pskel& /* connectinterface */);

    // Constructor.
    //
    connections_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::connectinterface_pskel* connectinterface_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::connections_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class connectinterface_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    usesport (const ::ossie::UsesPort&);

    virtual void
    providesport (const ::ossie::ProvidesPort&);

    virtual void
    componentsupportedinterface (const ::ossie::ComponentSupportedInterface&);

    virtual void
    findby (const ::ossie::FindBy&);

    virtual void
    id (const ::std::string&);

    virtual ::ossie::Connection
    post_connectinterface () = 0;

    // Parser construction API.
    //
    void
    usesport_parser (::sad::usesport_pskel&);

    void
    providesport_parser (::sad::providesport_pskel&);

    void
    componentsupportedinterface_parser (::sad::componentsupportedinterface_pskel&);

    void
    findby_parser (::sad::findby_pskel&);

    void
    id_parser (::xml_schema::string_pskel&);

    void
    parsers (::sad::usesport_pskel& /* usesport */,
             ::sad::providesport_pskel& /* providesport */,
             ::sad::componentsupportedinterface_pskel& /* componentsupportedinterface */,
             ::sad::findby_pskel& /* findby */,
             ::xml_schema::string_pskel& /* id */);

    // Constructor.
    //
    connectinterface_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    virtual bool
    _attribute_impl_phase_one (const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&,
                               const ::xml_schema::ro_string&);


    protected:
    ::sad::usesport_pskel* usesport_parser_;
    ::sad::providesport_pskel* providesport_parser_;
    ::sad::componentsupportedinterface_pskel* componentsupportedinterface_parser_;
    ::sad::findby_pskel* findby_parser_;
    ::xml_schema::string_pskel* id_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::connectinterface_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[3UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class usesport_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    usesidentifier (const ::std::string&);

    virtual void
    componentinstantiationref (const ::std::string&);

    virtual void
    devicethatloadedthiscomponentref (const ::std::string&);

    virtual void
    deviceusedbythiscomponentref (const ::std::pair<std::string, std::string>&);

    virtual void
    findby (const ::ossie::FindBy&);

    virtual ::ossie::UsesPort
    post_usesport () = 0;

    // Parser construction API.
    //
    void
    usesidentifier_parser (::xml_schema::string_pskel&);

    void
    componentinstantiationref_parser (::sad::componentinstantiationref_pskel&);

    void
    devicethatloadedthiscomponentref_parser (::sad::devicethatloadedthiscomponentref_pskel&);

    void
    deviceusedbythiscomponentref_parser (::sad::deviceusedbythiscomponentref_pskel&);

    void
    findby_parser (::sad::findby_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* usesidentifier */,
             ::sad::componentinstantiationref_pskel& /* componentinstantiationref */,
             ::sad::devicethatloadedthiscomponentref_pskel& /* devicethatloadedthiscomponentref */,
             ::sad::deviceusedbythiscomponentref_pskel& /* deviceusedbythiscomponentref */,
             ::sad::findby_pskel& /* findby */);

    // Constructor.
    //
    usesport_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::xml_schema::string_pskel* usesidentifier_parser_;
    ::sad::componentinstantiationref_pskel* componentinstantiationref_parser_;
    ::sad::devicethatloadedthiscomponentref_pskel* devicethatloadedthiscomponentref_parser_;
    ::sad::deviceusedbythiscomponentref_pskel* deviceusedbythiscomponentref_parser_;
    ::sad::findby_pskel* findby_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::usesport_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[3UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class providesport_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    providesidentifier (const ::std::string&);

    virtual void
    componentinstantiationref (const ::std::string&);

    virtual void
    devicethatloadedthiscomponentref (const ::std::string&);

    virtual void
    deviceusedbythiscomponentref (const ::std::pair<std::string, std::string>&);

    virtual void
    findby (const ::ossie::FindBy&);

    virtual ::ossie::ProvidesPort
    post_providesport () = 0;

    // Parser construction API.
    //
    void
    providesidentifier_parser (::xml_schema::string_pskel&);

    void
    componentinstantiationref_parser (::sad::componentinstantiationref_pskel&);

    void
    devicethatloadedthiscomponentref_parser (::sad::devicethatloadedthiscomponentref_pskel&);

    void
    deviceusedbythiscomponentref_parser (::sad::deviceusedbythiscomponentref_pskel&);

    void
    findby_parser (::sad::findby_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* providesidentifier */,
             ::sad::componentinstantiationref_pskel& /* componentinstantiationref */,
             ::sad::devicethatloadedthiscomponentref_pskel& /* devicethatloadedthiscomponentref */,
             ::sad::deviceusedbythiscomponentref_pskel& /* deviceusedbythiscomponentref */,
             ::sad::findby_pskel& /* findby */);

    // Constructor.
    //
    providesport_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::xml_schema::string_pskel* providesidentifier_parser_;
    ::sad::componentinstantiationref_pskel* componentinstantiationref_parser_;
    ::sad::devicethatloadedthiscomponentref_pskel* devicethatloadedthiscomponentref_parser_;
    ::sad::deviceusedbythiscomponentref_pskel* deviceusedbythiscomponentref_parser_;
    ::sad::findby_pskel* findby_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::providesport_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[3UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class componentsupportedinterface_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    supportedidentifier (const ::std::string&);

    virtual void
    componentinstantiationref (const ::std::string&);

    virtual void
    findby (const ::ossie::FindBy&);

    virtual ::ossie::ComponentSupportedInterface
    post_componentsupportedinterface () = 0;

    // Parser construction API.
    //
    void
    supportedidentifier_parser (::xml_schema::string_pskel&);

    void
    componentinstantiationref_parser (::sad::componentinstantiationref_pskel&);

    void
    findby_parser (::sad::findby_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* supportedidentifier */,
             ::sad::componentinstantiationref_pskel& /* componentinstantiationref */,
             ::sad::findby_pskel& /* findby */);

    // Constructor.
    //
    componentsupportedinterface_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::xml_schema::string_pskel* supportedidentifier_parser_;
    ::sad::componentinstantiationref_pskel* componentinstantiationref_parser_;
    ::sad::findby_pskel* findby_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::componentsupportedinterface_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[3UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };

  class externalports_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    port (const ossie::SoftwareAssembly::Port&);

    virtual ::std::vector<ossie::SoftwareAssembly::Port>
    post_externalports () = 0;

    // Parser construction API.
    //
    void
    port_parser (::sad::port_pskel&);

    void
    parsers (::sad::port_pskel& /* port */);

    // Constructor.
    //
    externalports_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::sad::port_pskel* port_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::externalports_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);
  };

  class port_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    description (const ::std::string&);

    virtual void
    usesidentifier (const ::std::string&);

    virtual void
    providesidentifier (const ::std::string&);

    virtual void
    supportedidentifier (const ::std::string&);

    virtual void
    componentinstantiationref (const ::std::string&);

    virtual ossie::SoftwareAssembly::Port
    post_port () = 0;

    // Parser construction API.
    //
    void
    description_parser (::xml_schema::string_pskel&);

    void
    usesidentifier_parser (::xml_schema::string_pskel&);

    void
    providesidentifier_parser (::xml_schema::string_pskel&);

    void
    supportedidentifier_parser (::xml_schema::string_pskel&);

    void
    componentinstantiationref_parser (::sad::componentinstantiationref_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* description */,
             ::xml_schema::string_pskel& /* usesidentifier */,
             ::xml_schema::string_pskel& /* providesidentifier */,
             ::xml_schema::string_pskel& /* supportedidentifier */,
             ::sad::componentinstantiationref_pskel& /* componentinstantiationref */);

    // Constructor.
    //
    port_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::xml_schema::string_pskel* description_parser_;
    ::xml_schema::string_pskel* usesidentifier_parser_;
    ::xml_schema::string_pskel* providesidentifier_parser_;
    ::xml_schema::string_pskel* supportedidentifier_parser_;
    ::sad::componentinstantiationref_pskel* componentinstantiationref_parser_;

    protected:
    struct v_state_descr_
    {
      void (::sad::port_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string&,
        const ::xml_schema::ro_string*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[3UL];
      unsigned long size;
    };

    v_state_ v_state_first_;
    ::xsd::cxx::parser::pod_stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long& state,
                unsigned long& count,
                const ::xml_schema::ro_string& ns,
                const ::xml_schema::ro_string& n,
                const ::xml_schema::ro_string* t,
                bool start);

    void
    choice_0 (unsigned long& state,
              unsigned long& count,
              const ::xml_schema::ro_string& ns,
              const ::xml_schema::ro_string& n,
              const ::xml_schema::ro_string* t,
              bool start);
  };
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CXX___XML_XSD_SAD_PSKEL_H
